name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci --frozen-lockfile --include=dev
      - name: Solhint
        run: npm run lint:sol
