name: Solana Program CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
      - name: rust fmt
        run: cargo fmt --check
      - name: Build and test
        run: cargo check
